" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

" Plugins
Plugin 'kien/ctrlp.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'scrooloose/nerdtree'
Plugin 'sheerun/vim-polyglot'
Plugin 'yggdroot/indentline'
Plugin 'potatoesmaster/vim-movelines'

" End of Plugins
call vundle#end()
filetype plugin indent on

" Tree file navigation
map <F2> :NERDTreeToggle<CR>

" Show relative line numbers
set number
set relativenumber

" Autoreload
set autoread

" Show line numbers by default
set nu

" Syntax on
syntax on

" Airline
let g:airline_powerline_fonts = 1

" Show whitespaces
let g:indentLine_leadingSpaceEnabled = 1
let g:indentLine_leadingSpaceChar = '␣'
set listchars=trail:␣

" Whitespaces instead of tabs
set expandtab
set tabstop=4
set shiftwidth=4

" Remove default screen
set shortmess=I

" Window navigation
nmap <C-h> <C-w><C-h>
nmap <C-j> <C-w><C-j>
nmap <C-k> <C-w><C-k>
nmap <C-l> <C-w><C-l>
nmap <C-Left> <C-w><C-h>
nmap <C-Down> <C-w><C-j>
nmap <C-Up> <C-w><C-k>
nmap <C-Right> <C-w><C-l>

" Moving lines
let g:move_key_modifier = 'C'
nnoremap <S-Up> :m-2<CR>
nnoremap <S-Down> :m+<CR>
inoremap <S-Up> <Esc>:m-2<CR>
inoremap <S-Down> <Esc>:m+<CR>

" Tab character
inoremap <S-Tab> <C-V><Tab>

" Editor
set cursorline
